<?php

declare(strict_types=1);

require __DIR__ . '/src/bootstrap.php';
require __DIR__ . '/src/RouteBoxClient.php';

function sget(string $key, ?string $default = null): ?string{ $stmt=db()->prepare('SELECT value FROM settings WHERE key=?');$stmt->execute([$key]);$v=$stmt->fetchColumn();return $v===false?$default:(string)$v; }
function telegramApi(string $token,string $method,array $data=[]):array{ $ch=curl_init('https://api.telegram.org/bot'.$token.'/'.$method);if($ch===false)throw new RuntimeException('Could not initialize Telegram cURL.');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$data,CURLOPT_TIMEOUT=>35,CURLOPT_CONNECTTIMEOUT=>10]);$raw=curl_exec($ch);$error=curl_error($ch);curl_close($ch);if($raw===false)throw new RuntimeException('Telegram connection failed: '.($error?:'unknown cURL error'));$json=json_decode($raw,true);if(!is_array($json)||empty($json['ok']))throw new RuntimeException($json['description']??'Telegram API error');return is_array($json['result']??null)?$json['result']:[]; }
function normalizeLang(?string $lang):string{return str_starts_with(strtolower((string)$lang),'fa')?'fa':'en';}
function userLang(int $id):string{ $s=db()->prepare('SELECT language FROM telegram_users WHERE id=?');$s->execute([$id]);$v=(string)($s->fetchColumn()?:'');return $v==='fa'||$v==='en'?$v:'en'; }
function setUserLang(int $id,string $lang):void{db()->prepare('UPDATE telegram_users SET language=? WHERE id=?')->execute([$lang,$id]);}
function buttonText(string $key,string $lang,string $fallback):string{ $s=db()->prepare('SELECT text_fa,text_en FROM telegram_buttons WHERE action_key=? AND enabled=1');$s->execute([$key]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)return $fallback;return (string)($lang==='fa'?$r['text_fa']:$r['text_en']); }
function allButtons(string $lang):array{ $rows=db()->query('SELECT action_key,text_fa,text_en FROM telegram_buttons WHERE enabled=1 ORDER BY sort_order,id')->fetchAll(PDO::FETCH_ASSOC);$out=[];foreach($rows as $r){$out[(string)$r['action_key']]=(string)($lang==='fa'?$r['text_fa']:$r['text_en']);}return $out; }
function upsertTelegramUser(array $user):int{ $now=time();$stmt=db()->prepare('INSERT INTO telegram_users(telegram_id,username,first_name,created_at,last_seen,language) VALUES(?,?,?,?,?,?) ON CONFLICT(telegram_id) DO UPDATE SET username=excluded.username,first_name=excluded.first_name,last_seen=excluded.last_seen');$lang=normalizeLang($user['language_code']??'');$stmt->execute([(string)$user['id'],$user['username']??null,$user['first_name']??null,$now,$now,$lang]);$lookup=db()->prepare('SELECT id FROM telegram_users WHERE telegram_id=?');$lookup->execute([(string)$user['id']]);return (int)$lookup->fetchColumn(); }
function provisionUser(int $userId,string $telegramId,?int $planId=null):array{ $used=db()->prepare('SELECT COUNT(*) FROM provisions WHERE telegram_user_id=?');$used->execute([$userId]);if((int)$used->fetchColumn()>0)throw new RuntimeException('This account already has a service.');$durationSeconds=0;$quotaBytes=null;$planName='Free trial';if($planId!==null){$p=db()->prepare('SELECT * FROM plans WHERE id=? AND enabled=1');$p->execute([$planId]);$plan=$p->fetch(PDO::FETCH_ASSOC);if(!$plan)throw new RuntimeException('This plan is no longer available.');$durationSeconds=max(1,(int)$plan['duration_days'])*86400;$q=(float)$plan['quota_gb'];if($q>0)$quotaBytes=(int)round($q*1024*1024*1024);$planName=(string)$plan['name'];}else{$durationSeconds=max(1,(int)sget('trial_hours','12'))*3600;}$servers=db()->query('SELECT * FROM routebox_servers WHERE enabled=1 ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);if(!$servers)throw new RuntimeException('No active RouteBox server is configured.');$expiresAt=time()+$durationSeconds;$peerName='user'.$telegramId;$output=[];$createdPeers=[];try{foreach($servers as $server){$client=new RouteBoxClient((string)$server['base_url'],dec((string)$server['user_enc']),dec((string)$server['pass_enc']),(bool)$server['verify_tls']);$peer=null;foreach($client->peers() as $candidate){if(($candidate['name']??'')===$peerName){$peer=$candidate;break;}}$createdHere=false;if($peer===null){$peer=$client->createPeer($peerName);$createdHere=true;}$publicKey=(string)($peer['public_key']??$peer['publicKey']??'');if($publicKey==='')throw new RuntimeException('RouteBox did not return a public key.');if($createdHere)$createdPeers[]=[$client,$publicKey];$client->setExpiry($publicKey,$expiresAt,$quotaBytes);$config=$client->config($publicKey);db()->prepare('INSERT OR REPLACE INTO provisions(telegram_user_id,server_id,peer_name,public_key,expires_at,created_at) VALUES(?,?,?,?,?,?)')->execute([$userId,$server['id'],$peerName,$publicKey,$expiresAt,time()]);$output[]=['server'=>(string)$server['name'],'conf'=>$config,'expires'=>$expiresAt,'plan'=>$planName];}}catch(Throwable $e){foreach($createdPeers as [$client,$publicKey]){try{$client->deletePeer($publicKey);}catch(Throwable $rollback){log_event('error','Provision rollback failed: '.$rollback->getMessage());}}throw $e;}log_event('info','Provisioned Telegram user '.$telegramId.' with '.$planName);return $output; }
function planButtons():array{ $plans=db()->query('SELECT id,name,duration_days,quota_gb FROM plans WHERE enabled=1 ORDER BY sort_order,id')->fetchAll(PDO::FETCH_ASSOC);$buttons=[];foreach($plans as $p){$q=(float)$p['quota_gb']>0?rtrim(rtrim(number_format((float)$p['quota_gb'],1,'.',''),'0'),'.').'GB':'∞';$buttons[]=['text'=>'🚀 '.$p['name'].' • '.$p['duration_days'].' days • '.$q,'callback_data'=>'plan:'.$p['id']];}return $buttons; }
function sendMenu(string $token,$chatId,int $userId):void{ $lang=userLang($userId);$b=allButtons($lang);$keyboard=[];foreach(planButtons() as $row)$keyboard[]=[['text'=>$row['text'],'callback_data'=>$row['callback_data']]];$keyboard[]=[['text'=>$b['trial']??($lang==='fa'?'🎁 دریافت تست رایگان':'🎁 Get free trial'), 'callback_data'=>'trial'],['text'=>$b['account']??($lang==='fa'?'👤 حساب من':'👤 My account'),'callback_data'=>'account']];$keyboard[]=[['text'=>$b['language']??($lang==='fa'?'🌐 تغییر زبان':'🌐 Language'),'callback_data'=>'language']];$welcome=(string)sget($lang==='fa'?'welcome_fa':'welcome_en', $lang==='fa'?'🚀 RouteBox Telegram Bot\n\nسلام 👋\nسرویس موردنظر را انتخاب کنید:':'🚀 RouteBox Telegram Bot\n\nHello 👋\nChoose a service:');telegramApi($token,'sendMessage',['chat_id'=>$chatId,'text'=>$welcome,'reply_markup'=>json_encode(['inline_keyboard'=>$keyboard],JSON_UNESCAPED_UNICODE)]); }
$storedToken=sget('telegram_token');if(!$storedToken)exit("Telegram token is not configured\n");$token=dec($storedToken);@mkdir(__DIR__.'/storage',0700,true);$offset=(int)(@file_get_contents(__DIR__.'/storage/update.offset')?:0);
while(true){try{$updates=telegramApi($token,'getUpdates',['offset'=>$offset,'timeout'=>25,'allowed_updates'=>json_encode(['message','callback_query'])]);foreach($updates as $update){$offset=(int)$update['update_id']+1;file_put_contents(__DIR__.'/storage/update.offset',(string)$offset,LOCK_EX);$message=$update['message']??null;$callback=$update['callback_query']??null;$chatId=$message['chat']['id']??$callback['message']['chat']['id']??null;$from=$message['from']??$callback['from']??null;if($chatId===null||!is_array($from))continue;$userId=upsertTelegramUser($from);$text=(string)($message['text']??'');
if($message&&($text==='/start'||str_starts_with($text,'/start '))){sendMenu($token,$chatId,$userId);continue;}
if($message&&$text==='/menu'){sendMenu($token,$chatId,$userId);continue;}
if($message&&$text==='/account'){$lang=userLang($userId);$stmt=db()->prepare('SELECT COUNT(*) FROM provisions WHERE telegram_user_id=? AND expires_at>?');$stmt->execute([$userId,time()]);$active=(int)$stmt->fetchColumn();telegramApi($token,'sendMessage',['chat_id'=>$chatId,'text'=>$lang==='fa'?"👤 حساب شما\n\n🟢 سرویس فعال: {$active}":"👤 Your account\n\n🟢 Active services: {$active}"]);continue;}
if($message&&$text==='/language'){telegramApi($token,'sendMessage',['chat_id'=>$chatId,'text'=>'🌐 Language / زبان','reply_markup'=>json_encode(['inline_keyboard'=>[[['text'=>'🇮🇷 فارسی','callback_data'=>'lang:fa'],['text'=>'🇬🇧 English','callback_data'=>'lang:en']]]],JSON_UNESCAPED_UNICODE)]);continue;}
if(!$callback)continue;telegramApi($token,'answerCallbackQuery',['callback_query_id'=>$callback['id']]);$action=(string)($callback['data']??'');
if($action==='language'){telegramApi($token,'sendMessage',['chat_id'=>$chatId,'text'=>'🌐 Language / زبان','reply_markup'=>json_encode(['inline_keyboard'=>[[['text'=>'🇮🇷 فارسی','callback_data'=>'lang:fa'],['text'=>'🇬🇧 English','callback_data'=>'lang:en']]]],JSON_UNESCAPED_UNICODE)]);continue;}
if(str_starts_with($action,'lang:')){$lang=substr($action,5);if(!in_array($lang,['fa','en'],true))$lang='en';setUserLang($userId,$lang);telegramApi($token,'sendMessage',['chat_id'=>$chatId,'text'=>$lang==='fa'?'✅ زبان فارسی فعال شد.':'✅ English language enabled.']);sendMenu($token,$chatId,$userId);continue;}
if($action==='account'){$lang=userLang($userId);$stmt=db()->prepare('SELECT COUNT(*) FROM provisions WHERE telegram_user_id=? AND expires_at>?');$stmt->execute([$userId,time()]);$active=(int)$stmt->fetchColumn();telegramApi($token,'sendMessage',['chat_id'=>$chatId,'text'=>$lang==='fa'?"👤 حساب شما\n\n🟢 سرویس فعال: {$active}":"👤 Your account\n\n🟢 Active services: {$active}"]);continue;}
$planId=null;if(str_starts_with($action,'plan:')){$parsed=(int)substr($action,5);if($parsed>0)$planId=$parsed;}if($action==='trial'||$planId!==null){$lang=userLang($userId);try{$items=provisionUser($userId,(string)$from['id'],$planId);foreach($items as $item){$tmp=tempnam(sys_get_temp_dir(),'rbt');if($tmp===false)throw new RuntimeException('Could not create temporary config file.');file_put_contents($tmp,$item['conf']);try{$caption=$lang==='fa'?(($planId===null?'🎁 تست فعال شد':'🚀 سرویس فعال شد')."\n\n📦 پلن: {$item['plan']}\n🖥️ سرور: {$item['server']}\n⏱️ اعتبار تا: ".date('Y-m-d H:i',$item['expires'])):(($planId===null?'🎁 Trial activated':'🚀 Service activated')."\n\n📦 Plan: {$item['plan']}\n🖥️ Server: {$item['server']}\n⏱️ Valid until: ".date('Y-m-d H:i',$item['expires']));telegramApi($token,'sendDocument',['chat_id'=>$chatId,'document'=>new CURLFile($tmp,'text/plain','RouteBox-'.$item['server'].'.conf'),'caption'=>$caption]);}finally{@unlink($tmp);}}}catch(Throwable $e){log_event('error','Provision: '.$e->getMessage());telegramApi($token,'sendMessage',['chat_id'=>$chatId,'text'=>($lang==='fa'?'❌ خطا: ':'❌ Error: ').$e->getMessage()]);}}
}}
}catch(Throwable $e){log_event('error','Telegram worker: '.$e->getMessage());sleep(3);}}
