<?php

return [
    'app_name' => 'RouteBox Telegram Bot',
    'version' => '0.1.0-beta.1',
    'timezone' => 'Asia/Tehran',
    'db' => __DIR__ . '/../storage/database.sqlite',
    // 32 random bytes, base64 encoded. Generated by install.sh.
    'app_key' => '',
    'admin_user' => 'admin',
    'admin_password_hash' => '',
    'telegram' => [
        'poll_timeout' => 25,
    ],
    'security' => [
        'session_name' => 'rbt_session',
        'cookie_secure' => false,
    ],
];
