<?php

declare(strict_types=1);
namespace RouteBox\Admin;
use PDO; use RouteBox\Services\TrialService;
require_once __DIR__.'/../Services/TrialService.php';
final class TrialAdminPanel{
 private static bool $started=false; private static function e(string $v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
 public static function boot(PDO $db):void{if(self::$started)return;self::$started=true;TrialService::ensureSchema($db);if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'&&isset($_POST['atd_trial_action'])){require_admin();verify_csrf();try{$a=(string)$_POST['atd_trial_action'];if($a==='save_plan')TrialService::savePlan($db,(int)$_POST['category_id'],(int)$_POST['plan_id'],isset($_POST['enabled']));elseif($a==='delete_trial')TrialService::deleteExpired($db,(int)$_POST['trial_id']);else throw new \RuntimeException('Invalid Trial action.');$_SESSION['flash']='✓ Trial action completed.';}catch(\Throwable $x){$_SESSION['flash']='❌ '.$x->getMessage();}$u=(string)($_POST['return_url']??'/?section=users');header('Location: '.$u);exit;}ob_start(static function(string $html)use($db):string{$s=(string)($_GET['section']??'');$lang=(string)($_GET['lang']??'fa');if($s==='bot')$html.=self::settings($db,$lang);if($s==='users')$html.=self::trials($db,$lang);return $html;});}
 private static function settings(PDO $db,string $lang):string{$fa=$lang==='fa';$csrf=self::e(csrf_token());$h='<section class="card" style="margin:20px 0"><div class="section-head"><div><div class="eyebrow">ATD PANEL · BOT</div><h2>🎁 '.($fa?'Trial هر Provider':'Provider Free Trials').'</h2><p>'.($fa?'برای هر Provider یک Plan واقعی از همان Catalog انتخاب کنید.':'Choose one real Catalog Plan for each Provider.').'</p></div></div><div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px">';foreach(TrialService::categoriesWithPlans($db) as $c){$h.='<form method="post" style="border:1px solid var(--line);border-radius:14px;padding:14px"><input type="hidden" name="csrf_token" value="'.$csrf.'"><input type="hidden" name="atd_trial_action" value="save_plan"><input type="hidden" name="category_id" value="'.(int)$c['id'].'"><input type="hidden" name="return_url" value="/?section=bot"><strong>'.self::e($fa?(string)$c['name_fa']:(string)$c['name_en']).'</strong><select name="plan_id" style="width:100%;margin-top:10px"><option value="">— '.($fa?'بدون Trial':'No Trial').' —</option>';foreach($c['plans'] as $p){$sel=(int)($c['trial_plan_id']??0)===(int)$p['id']?' selected':'';$h.='<option value="'.(int)$p['id'].'"'.$sel.'>'.self::e($fa?(string)$p['display_name_fa']:(string)$p['display_name_en']).' · '.(int)$p['duration_days'].'d</option>';}$h.='</select><label style="display:block;margin-top:8px"><input type="checkbox" name="enabled" '.(!empty($c['trial_plan_id'])?'checked':'').'> '.($fa?'فعال':'Enabled').'</label><button class="btn btn-primary" style="margin-top:10px">'.($fa?'ذخیره':'Save').'</button></form>';}$h.='</div></section>';return $h;}
 private static function trials(PDO $db,string $lang):string{$fa=$lang==='fa';$csrf=self::e(csrf_token());$rows=TrialService::listTrials($db);$h='<section class="card" style="margin:20px 0"><div class="section-head"><div><div class="eyebrow">ATD PANEL · USERS</div><h2>🎁 Trials</h2><p>'.($fa?'Trialهای منقضی‌شده را حذف کنید؛ سابقه دریافت Trial باقی می‌ماند.':'Delete expired Trial resources; the permanent claim remains.').'</p></div></div><div style="overflow:auto"><table style="width:100%"><thead><tr><th>ID</th><th>'.($fa?'کاربر':'User').'</th><th>Provider</th><th>Plan</th><th>Status</th><th>Expiry</th><th></th></tr></thead><tbody>';foreach($rows as $r){$expired=$r['expires_at']!==null&&(int)$r['expires_at']<=time()&&$r['status']!=='deleted';$name=trim((string)($r['first_name']??''))?:((string)($r['username']??'')!==''?'@'.$r['username']:(string)$r['telegram_id']);$h.='<tr><td>'.(int)$r['id'].'</td><td>'.self::e($name).'</td><td>'.self::e((string)$r['provider_key']).'</td><td>'.self::e($fa?(string)($r['display_name_fa']??''):(string)($r['display_name_en']??'')).'</td><td>'.self::e((string)$r['status']).'</td><td>'.($r['expires_at']?date('Y-m-d H:i',(int)$r['expires_at']):'—').'</td><td>';if($expired)$h.='<form method="post"><input type="hidden" name="csrf_token" value="'.$csrf.'"><input type="hidden" name="atd_trial_action" value="delete_trial"><input type="hidden" name="trial_id" value="'.(int)$r['id'].'"><input type="hidden" name="return_url" value="/?section=users"><button class="btn btn-secondary">🗑 '.($fa?'حذف':'Delete').'</button></form>';else $h.='<span style="color:var(--muted)">'.($fa?'فعال':'Active').'</span>';$h.='</td></tr>';}if(!$rows)$h.='<tr><td colspan="7">'.($fa?'Trialی ثبت نشده است.':'No trials found.').'</td></tr>';return $h.'</tbody></table></div></section>';}
}
