<?php
declare(strict_types=1);
if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) !== 'index.php') return;
require_once __DIR__.'/RouteBoxClient.php';
function rbt_setting(string $k,string $d=''):string{$q=db()->prepare('SELECT value FROM settings WHERE key=?');$q->execute([$k]);$v=$q->fetchColumn();return $v===false?$d:(string)$v;}
function rbt_set(string $k,string $v):void{db()->prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value")->execute([$k,$v]);}
function rbt_backups():array{$d='/var/backups/routebox-telegram-bot';$out=[];foreach(glob($d.'/routebox-telegram-bot-v*.tar.gz')?:[] as $f){$n=basename($f);if(preg_match('/^routebox-telegram-bot-v([0-9A-Za-z.-]+)(-pre-update)?-(\d{8})-(\d{6})\.tar\.gz$/',$n,$m))$out[]=['name'=>$n,'version'=>$m[1],'ts'=>$m[3].$m[4],'size'=>(int)(filesize($f)?:0)];}usort($out,fn($a,$b)=>strcmp($b['ts'],$a['ts']));return array_slice($out,0,10);}
function rbt_bytes(int $n):string{$u=['B','KB','MB','GB'];$i=0;while($n>=1024&&$i<3){$n/=1024;$i++;}return number_format($n,$i?'1':'0')." {$u[$i]}";}
function rbt_go(string $s='tools'):never{header('Location:/?section='.rawurlencode($s));exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&!empty($_SESSION['admin'])&&isset($_POST['extra_action'])){verify_csrf();try{$a=(string)$_POST['extra_action'];
 if($a==='guide'){foreach(['guide_fa','guide_en','android_url','ios_url','windows_url','macos_url'] as $k)rbt_set($k,trim((string)($_POST[$k]??'')));$_SESSION['flash']='✓ Guide settings saved.';rbt_go();}
 if($a==='server'){ $id=(int)$_POST['server_id'];$q=db()->prepare('SELECT * FROM routebox_servers WHERE id=?');$q->execute([$id]);$s=$q->fetch(PDO::FETCH_ASSOC);if(!$s)throw new RuntimeException('RouteBox not found.');$name=trim((string)$_POST['name']);$url=rtrim(trim((string)$_POST['url']),'/');$user=trim((string)$_POST['username']);$pass=(string)$_POST['password'];$verify=isset($_POST['verify_tls'])?1:0;if($pass==='')$pass=dec($s['pass_enc']);$c=new RouteBoxClient($url,$user,$pass,(bool)$verify);$c->validateIntegration();$c->smokeTest('rbt-admin-test');db()->prepare('UPDATE routebox_servers SET name=?,base_url=?,user_enc=?,pass_enc=?,verify_tls=? WHERE id=?')->execute([$name,$url,enc($user),enc($pass),$verify,$id]);$_SESSION['flash']='✓ RouteBox updated and tested.';rbt_go('servers');}
 if($a==='test'){ $q=db()->prepare('SELECT * FROM routebox_servers WHERE id=?');$q->execute([(int)$_POST['server_id']]);$s=$q->fetch(PDO::FETCH_ASSOC);if(!$s)throw new RuntimeException('RouteBox not found.');$c=new RouteBoxClient($s['base_url'],dec($s['user_enc']),dec($s['pass_enc']),(bool)$s['verify_tls']);$c->validateIntegration();$c->smokeTest('rbt-admin-test');$_SESSION['flash']='✓ RouteBox + AWG test passed.';rbt_go('servers');}
 if($a==='backup'){ $o=shell_exec('sudo -n /usr/local/sbin/routebox-telegram-bot-backup 2>&1');if(!preg_match('/\/var\/backups\/routebox-telegram-bot\/routebox-telegram-bot-v[^\s]+\.tar\.gz/',$o??''))throw new RuntimeException(trim((string)$o)?:'Backup failed.');$_SESSION['flash']='✓ Backup created.';rbt_go();}
 if($a==='delete'){ $n=basename((string)$_POST['backup']);if(!preg_match('/^routebox-telegram-bot-v[0-9A-Za-z.-]+(?:-pre-update)?-\d{8}-\d{6}\.tar\.gz$/',$n))throw new RuntimeException('Invalid backup.');shell_exec('sudo -n /usr/local/sbin/routebox-telegram-bot-backup delete '.escapeshellarg($n).' 2>&1');$_SESSION['flash']='✓ Backup deleted.';rbt_go();}
 if($a==='restore'){ $n=basename((string)$_POST['backup']);if(!preg_match('/^routebox-telegram-bot-v[0-9A-Za-z.-]+(?:-pre-update)?-\d{8}-\d{6}\.tar\.gz$/',$n))throw new RuntimeException('Invalid backup.');shell_exec('nohup sudo -n /usr/local/sbin/routebox-telegram-bot-restore '.escapeshellarg($n).' >/tmp/routebox-restore.log 2>&1 &');$_SESSION['flash']='✓ Restore started; panel may disconnect.';rbt_go();}
 }catch(Throwable $e){$_SESSION['flash']='❌ '.$e->getMessage();rbt_go();}}
ob_start(function(string $html):string{$sec=(string)($_GET['section']??'');$csrf=h(csrf_token());$servers=db()->query('SELECT * FROM routebox_servers ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);$rows='';foreach(rbt_backups() as $b){$n=h($b['name']);$ts=$b['ts'];$date=h(substr($ts,0,4).'-'.substr($ts,4,2).'-'.substr($ts,6,2).' '.substr($ts,8,2).':'.substr($ts,10,2).':'.substr($ts,12,2));$rows.='<tr><td><code>'.$n.'</code></td><td>'.h($b['version']).'</td><td>'.$date.'</td><td>'.rbt_bytes($b['size']).'</td><td><a class="btn btn-secondary" href="/backup-download.php?name='.rawurlencode($b['name']).'">Download</a> <form method="post" style="display:inline"><input type="hidden" name="csrf_token" value="'.$csrf.'"><input type="hidden" name="extra_action" value="restore"><input type="hidden" name="backup" value="'.$n.'"><button class="btn btn-secondary" onclick="return confirm(\'Restore this backup?\')">Restore</button></form> <form method="post" style="display:inline"><input type="hidden" name="csrf_token" value="'.$csrf.'"><input type="hidden" name="extra_action" value="delete"><input type="hidden" name="backup" value="'.$n.'"><button class="btn btn-secondary" onclick="return confirm(\'Delete this backup?\')">Delete</button></form></td></tr>';}$rows=$rows?:'<tr><td colspan="5">No backups found.</td></tr>';
$guid='<section class="rbt-extra-page card"><h2>Usage guide</h2><p>Editable links and Persian/English guide.</p><form method="post"><input type="hidden" name="csrf_token" value="'.$csrf.'"><input type="hidden" name="extra_action" value="guide"><div class="grid">';foreach([['android_url','Android'],['ios_url','iPhone / iPad'],['windows_url','Windows'],['macos_url','macOS']] as [$k,$l])$guid.='<div class="field"><label>'.$l.' URL</label><input name="'.$k.'" value="'.h(rbt_setting($k)).'"></div>';$guid.='<div class="field"><label>راهنمای فارسی</label><textarea name="guide_fa" rows="7">'.h(rbt_setting('guide_fa')).'</textarea></div><div class="field"><label>English guide</label><textarea name="guide_en" rows="7">'.h(rbt_setting('guide_en')).'</textarea></div></div><button class="btn btn-primary">Save guide</button></form></section>';
$sv='<section class="rbt-extra-page card"><h2>RouteBox settings</h2><p>Edit Name, URL, Username, Password and Verify TLS. Save also runs connection + AWG smoke test.</p>';foreach($servers as $s){$id=(int)$s['id'];$sv.='<form method="post" style="margin-top:15px;padding:15px;border:1px solid var(--border);border-radius:14px"><input type="hidden" name="csrf_token" value="'.$csrf.'"><input type="hidden" name="extra_action" value="server"><input type="hidden" name="server_id" value="'.$id.'"><div class="grid"><div class="field"><label>Name</label><input name="name" value="'.h($s['name']).'" required></div><div class="field"><label>URL</label><input name="url" value="'.h($s['base_url']).'" required></div><div class="field"><label>Username</label><input name="username" value="'.h(dec($s['user_enc'])).'" required></div><div class="field"><label>Password</label><input name="password" type="password" placeholder="unchanged if empty"></div></div><label class="switch"><input type="checkbox" name="verify_tls" '.((bool)$s['verify_tls']?'checked':'').'><span>Verify TLS</span></label><button class="btn btn-primary">Save & Test</button></form><form method="post" style="margin-top:6px"><input type="hidden" name="csrf_token" value="'.$csrf.'"><input type="hidden" name="extra_action" value="test"><input type="hidden" name="server_id" value="'.$id.'"><button class="btn btn-secondary">Test connection</button></form>';}$sv.='</section>';
$tools='<section class="rbt-extra-page card"><div class="section-head"><div><h2>Backup & Restore</h2><p>Manual backups, pre-update snapshots, restore, download and delete.</p></div><form method="post"><input type="hidden" name="csrf_token" value="'.$csrf.'"><input type="hidden" name="extra_action" value="backup"><button class="btn btn-primary">Create backup</button></form></div><div style="overflow:auto"><table style="width:100%"><thead><tr><th>File</th><th>Version</th><th>Date / time</th><th>Size</th><th>Actions</th></tr></thead><tbody>'.$rows.'</tbody></table></div><p class="help">Only the newest 10 backups are retained. Backup files live outside the public web root.</p></section>'.$guid.$sv;
$nav='<a href="/?section=tools" class="nav-link">🧰 Tools</a>';$done=false;if(preg_match('/(<a[^>]+href=["\']\/?\?section=updates["\'][^>]*>.*?<\/a>)/is',$html,$m,PREG_OFFSET_CAPTURE)){$p=$m[0][1]+strlen($m[0][0]);$html=substr($html,0,$p).$nav.substr($html,$p);$done=true;}if(!$done)$html=preg_replace('/<\/nav>/i',$nav.'</nav>',$html,1)??$html;
if($sec==='tools'){$page='<style>body.rbt-extra-mode .main>*{display:none!important}body.rbt-extra-mode .main>.rbt-extra-page{display:block!important}</style>'.$tools;$html=preg_replace('/<main([^>]*)>.*?<\/main>/is','<main$1 class="main rbt-extra-main">'.$page.'</main>',$html,1)??$html;$html=str_replace('<body','<body class="rbt-extra-mode"',$html);}else{$html=preg_replace('/<\/main>/i',$tools.'</main>',$html,1)??$html;}return $html;});
