<?php
declare(strict_types=1);
use RouteBox\Integrations\IBSng\IBSngSchema;
use RouteBox\Integrations\IBSng\IBSngService;
require_once __DIR__.'/Integrations/IBSng/IBSngClient.php';
require_once __DIR__.'/Integrations/IBSng/IBSngSchema.php';
require_once __DIR__.'/Integrations/IBSng/IBSngService.php';
IBSngSchema::ensure(db());
$section=(string)($_GET['section']??'');
if(!in_array($section,['ibsng','payments','coupons','broadcast'],true))return;
require_admin();
$svc=new IBSngService(db());$flash='';$error=false;$lookup=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  verify_csrf();$a=(string)($_POST['feature_action']??'');
  if($a==='add_server'){
   $name=trim((string)$_POST['name']);$host=trim((string)$_POST['host']);$user=trim((string)$_POST['username']);$pass=(string)$_POST['password'];$port=max(1,min(65535,(int)($_POST['port']??80)));$isp=trim((string)($_POST['isp_name']??'Main'))?:'Main';
   if($name===''||$host===''||$user===''||$pass==='')throw new RuntimeException('IBSng connection settings are incomplete.');
   db()->prepare('INSERT INTO ibsng_servers(name,host,port,admin_user_enc,admin_pass_enc,isp_name,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?)')->execute([$name,$host,$port,enc($user),enc($pass),$isp,time(),time()]);
   $id=(int)db()->lastInsertId();$r=$svc->test($id);$n=$svc->syncGroups($id);$flash='اتصال موفق شد؛ '.$n.' گروه از IBSng دریافت و همگام شد.';
  }elseif($a==='test'){$r=$svc->test((int)$_POST['id']);$flash='اتصال موفق است؛ '.count($r['groups']).' گروه از IBSng خوانده شد.';
  }elseif($a==='sync'){$n=$svc->syncGroups((int)$_POST['id']);$flash=$n.' گروه با موفقیت از IBSng همگام شد.';
  }elseif($a==='lookup'){$lookup=$svc->userInfo((int)$_POST['id'],trim((string)$_POST['username']));$flash='اطلاعات کاربر از IBSng دریافت شد.';
  }elseif($a==='create'){$server=(int)$_POST['id'];$group=trim((string)$_POST['group_name']);$username=trim((string)$_POST['new_username']);$password=(string)$_POST['new_password'];$r=$svc->createAccount($server,trim((string)$_POST['isp_name']),$group,$username,$password,(int)($_POST['credit']??0));$flash='کاربر با موفقیت در گروه '.$group.' ساخته شد: '.$username;
  }elseif($a==='toggle'){db()->prepare('UPDATE ibsng_servers SET enabled=1-enabled,updated_at=? WHERE id=?')->execute([time(),(int)$_POST['id']]);$flash='وضعیت سرور تغییر کرد.';
  }elseif($a==='delete'){db()->prepare('DELETE FROM ibsng_servers WHERE id=?')->execute([(int)$_POST['id']]);$flash='سرور حذف شد.';
  }elseif($a==='plan'){$svc->savePlan(['server_id'=>(int)$_POST['server_id'],'group_name'=>(string)$_POST['group_name'],'name_fa'=>(string)$_POST['name_fa'],'name_en'=>(string)$_POST['name_en'],'price'=>(int)$_POST['price'],'days'=>(int)$_POST['days'],'quota'=>(float)$_POST['quota'],'sort_order'=>(int)$_POST['sort_order']]);$flash='پلن IBSng ذخیره شد.';}
 }catch(Throwable $e){$error=true;$flash='خطا: '.$e->getMessage();log_event('error','IBSng module: '.$e->getMessage());}
}
function ia(string $a,int $id,string $label):string{return '<form method="post" style="display:inline"><input type="hidden" name="csrf_token" value="'.h(csrf_token()).'"><input type="hidden" name="feature_action" value="'.h($a).'"><input type="hidden" name="id" value="'.$id.'"><button>'.h($label).'</button></form>';}
$css='<style>body{margin:0;background:#070b16;color:#eef4ff;font-family:Tahoma,Arial;padding:28px}main{max-width:1250px;margin:auto}.card{background:#0f172a;border:1px solid #26344e;border-radius:18px;padding:20px;margin:16px 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}input,select{width:100%;box-sizing:border-box;padding:10px;background:#0a1120;color:#fff;border:1px solid #30415e;border-radius:8px;margin:6px 0 12px}button,.btn{background:#4f7cff;color:#fff;border:0;border-radius:8px;padding:9px 12px;text-decoration:none;cursor:pointer}.danger{background:#8b3042}.muted{color:#9aa9bf}.flash{padding:12px;background:#142846;border-radius:9px;margin:12px 0}.ok{border:1px solid #1f9d63}.err{border:1px solid #a33b4c}.table{width:100%;border-collapse:collapse}.table td,.table th{text-align:right;padding:10px;border-bottom:1px solid #22304a}.row{display:flex;gap:6px;flex-wrap:wrap}.security{font-size:12px;color:#9aa9bf;line-height:1.7;padding:11px 13px;border:1px solid #26344e;border-radius:10px;background:#0b1220}.badge{display:inline-block;padding:3px 7px;border-radius:999px;background:#17243b;color:#9fb7df;font-size:11px}.result{white-space:pre-wrap;direction:ltr;text-align:left;max-height:320px;overflow:auto;background:#080d18;border-radius:10px;padding:12px;font:12px monospace}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style>';
if($section==='ibsng'){
 $servers=db()->query('SELECT id,name,host,port,enabled,isp_name FROM ibsng_servers ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);
 $groups=db()->query('SELECT g.*,s.name server_name FROM ibsng_groups g JOIN ibsng_servers s ON s.id=g.ibsng_server_id ORDER BY s.id,g.group_name')->fetchAll(PDO::FETCH_ASSOC);
 $plans=db()->query("SELECT * FROM service_plans WHERE provider_key='ibsng' ORDER BY id")->fetchAll(PDO::FETCH_ASSOC);
 echo '<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IBSng — RouteBox</title>'.$css.'</head><body><main><a class="btn" href="/?section=dashboard">← پنل اصلی RouteBox</a><h1>🔵 مدیریت IBSng A1.24</h1><p class="muted">OpenVPN / Cisco / L2TP — یک اکانت IBSng برای هر سه سرویس</p>'.($flash?'<div class="flash '.($error?'err':'ok').'">'.h($flash).'</div>':'');
 echo '<div class="card"><h2>اتصال به IBSng</h2><form method="post" autocomplete="off"><input type="hidden" name="csrf_token" value="'.h(csrf_token()).'"><input type="hidden" name="feature_action" value="add_server"><div class="grid"><div>نام سرور<input name="name" required maxlength="80"></div><div>IP / Host<input name="host" required autocomplete="off"></div><div>Admin Username<input name="username" required autocomplete="off"></div><div>Admin Password<input name="password" type="password" required autocomplete="new-password"></div><div>Web Port<input name="port" type="number" min="1" max="65535" value="80"></div><div>ISP Name<input name="isp_name" value="Main" maxlength="80"></div></div><div class="security">🔐 اتصال A1.24 از Web Panel انجام می‌شود؛ پورت پیش‌فرض 80 است. Username و Password با SecretBox ذخیره می‌شوند و در UI و لاگ نمایش داده نمی‌شوند. نیازی به باز کردن 1235/1237 نیست.</div><br><button type="submit">🔗 اتصال + Sync گروه‌ها</button></form></div>';
 echo '<div class="card"><h2>سرورهای IBSng</h2>';if(!$servers)echo '<p class="muted">هنوز سروری اضافه نشده است.</p>';else{echo '<table class="table"><tr><th>نام</th><th>Host</th><th>Admin</th><th>وضعیت</th><th>عملیات</th></tr>';foreach($servers as $s){echo '<tr><td>'.h($s['name']).'</td><td>'.h($s['host']).' <span class="badge">WEB '.(int)$s['port'].'</span></td><td>••••••</td><td>'.((int)$s['enabled']?'فعال':'غیرفعال').'</td><td><div class="row">'.ia('test',(int)$s['id'],'Test').ia('sync',(int)$s['id'],'Sync Groups').ia('toggle',(int)$s['id'],'Toggle').ia('delete',(int)$s['id'],'Delete').'</div></td></tr>';}echo '</table>';}echo '</div>';
 echo '<div class="card"><h2>🔄 گروه‌های IBSng</h2><p class="muted">این لیست از خود IBSng خوانده شده است؛ برای به‌روزرسانی فقط Sync Groups را بزن.</p><table class="table"><tr><th>سرور</th><th>Group Name</th><th>Group ID</th><th>آخرین Sync</th></tr>';foreach($groups as $g)echo '<tr><td>'.h($g['server_name']).'</td><td><strong>'.h($g['group_name']).'</strong></td><td>'.h((string)($g['group_id']??'-')).'</td><td>'.date('Y-m-d H:i',(int)$g['synced_at']).'</td></tr>';echo '</table></div>';
 if($servers){echo '<div class="card"><h2>👤 تست User</h2><form method="post"><input type="hidden" name="csrf_token" value="'.h(csrf_token()).'"><input type="hidden" name="feature_action" value="lookup"><div class="grid"><div>IBSng Server<select name="id">';foreach($servers as $s)echo '<option value="'.(int)$s['id'].'">'.h($s['name']).'</option>';echo '</select></div><div>Username<input name="username" required></div></div><button>🔎 خواندن اطلاعات User</button></form>'.($lookup?'<div class="result">'.h(json_encode($lookup,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT)).'</div>':'').'</div>';
 echo '<div class="card"><h2>➕ تست ساخت User</h2><p class="muted">این عملیات واقعاً در IBSng یک User ایجاد می‌کند؛ فقط برای تست استفاده کن.</p><form method="post"><input type="hidden" name="csrf_token" value="'.h(csrf_token()).'"><input type="hidden" name="feature_action" value="create"><div class="grid"><div>IBSng Server<select name="id">';foreach($servers as $s)echo '<option value="'.(int)$s['id'].'">'.h($s['name']).'</option>';echo '</select></div><div>Group<select name="group_name">';foreach($groups as $g)echo '<option value="'.h($g['group_name']).'">'.h($g['server_name'].' / '.$g['group_name']).'</option>';echo '</select></div><div>Username جدید<input name="new_username" required></div><div>Password جدید<input name="new_password" type="password" required></div><div>ISP<input name="isp_name" value="Main"></div><div>Credit<input name="credit" type="number" value="0"></div></div><button>👤 ساخت User در IBSng</button></form></div>';
 if($groups){echo '<div class="card"><h2>📦 ساخت پلن</h2><form method="post"><input type="hidden" name="csrf_token" value="'.h(csrf_token()).'"><input type="hidden" name="feature_action" value="plan"><div class="grid"><div>Server<select name="server_id">';foreach($servers as $s)echo '<option value="'.(int)$s['id'].'">'.h($s['name']).'</option>';echo '</select></div><div>IBSng Group<select name="group_name">';foreach($groups as $g)echo '<option value="'.h($g['group_name']).'">'.h($g['server_name'].' / '.$g['group_name']).'</option>';echo '</select></div><div>نام پلن فارسی<input name="name_fa" placeholder="یک ماهه" required></div><div>نام پلن انگلیسی<input name="name_en" placeholder="1 Month" required></div><div>قیمت<input name="price" type="number" value="0"></div><div>روز<input name="days" type="number" value="30"></div><div>حجم GB<input name="quota" type="number" step="0.01" value="0"></div><div>ترتیب<input name="sort_order" type="number" value="10"></div></div><button>ذخیره پلن</button></form></div>';}}
 echo '<div class="card"><h2>پلن‌های ثبت‌شده</h2>';foreach($plans as $p)echo '<p>🔵 '.h($p['display_name_fa']).' → Group: <strong>'.h($p['provider_plan_key']).'</strong> → '.(int)$p['duration_days'].' روز</p>';if(!$plans)echo '<p class="muted">هنوز پلنی ثبت نشده.</p>';echo '</div></main></body></html>';exit;
}
if($section==='payments'){echo '<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8">'.$css.'</head><body><main><a class="btn" href="/?section=dashboard">← پنل</a><div class="card"><h1>💳 Payment</h1><p>Order → Coupon → Gateway → Verify → Provisioning</p></div></main></body></html>';exit;}
if($section==='coupons'){echo '<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8">'.$css.'</head><body><main><a class="btn" href="/?section=dashboard">← پنل</a><div class="card"><h1>🏷️ Coupons</h1></div></body></html>';exit;}
if($section==='broadcast'){echo '<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8">'.$css.'</head><body><main><a class="btn" href="/?section=dashboard">← پنل</a><div class="card"><h1>📣 Telegram Broadcast</h1></div></body></html>';exit;}
